# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Udacity project 2
email: janis.tidrikis@delfi.lv
description: > # this means to ignore newlines until "baseurl:"
  Udacity project 2 site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.udacity-project-2.com" # the base hostname & protocol for your site
author: Janis Tidriķis
author_skill: front-end ninja?
twitter_username: janist7
github_username:  janist7

# Build settings
markdown: kramdown
